baseURL = 'https://ajaysnotion.netlify.app'
languageCode = 'en-us'
title = ''
enableGitInfo=false

custom_css = ["css/style.css"]
custom_js = ["js/custom.js"]

[build]
writeStats = true

[outputFormats.CSS]
mediatype = "text/css"
isPlainText = true
notAlternative = true

[mediaTypes."text/css"]
suffixes = ["css"]

[outputs]
home = ["HTML", "CSS"]

[outputFormats]
  [outputFormats.HTML]
    mediaType = "text/html"
    isHTML = true
    isPlainText = false
    notAlternative = true
    noUgly = true
    minify = true